// app/dashboard/layout.tsx
import { ReactNode } from 'react';
import type { Metadata } from "next";
import Header from "@/components/layout/header";

export const metadata: Metadata = {
    title: "Home | My Site",
    description: "Generated by create next app",
  };

export default function DashboardLayout({ children }: { children: ReactNode }) {
  return (
    <div className="overflow-hidden">
      <Header />
      <div className="flex">
        {/* <Suspense fallback={<Loading />}> */}
          <div className="w-full ">
            <main className="w-full  ">{children}</main>
          </div>
        {/* </Suspense> */}
      </div>
    </div>
  );
}
